name: Full CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    name: Build, Test and Lint
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: task_tracker_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      QUARKUS_DATASOURCE_USERNAME: postgres
      QUARKUS_DATASOURCE_PASSWORD: postgres
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://localhost:5432/task_tracker_db
      QUARKUS_LIQUIBASE_MIGRATE_AT_START: true
      QUARKUS_LIQUIBASE_CHANGE_LOG: db/changelog/db.changelog-dev.yaml
      QUARKUS_LIQUIBASE_DEFAULT_SCHEMA: dev

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Grant execute permission to Gradle wrapper
        run: chmod +x ./gradlew

      - name: Build backend with Gradle
        run: ./gradlew build --info

      - name: Run backend tests
        run: ./gradlew test

      - name: Set up frontend dependencies
        working-directory: src/main/webui
        run: npm ci

      - name: Build frontend (Vite + Vue)
        working-directory: src/main/webui
        run: npm run build

      - name: Archive frontend build
        uses: actions/upload-artifact@v4
        with:
          name: frontend-dist
          path: src/main/webui/dist

      - name: Archive backend JAR
        uses: actions/upload-artifact@v4
        with:
          name: backend-jar
          path: build/libs/*.jar
