name: Full CI - Quarkus + Vite/Vue

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  backend:
    name: Backend (Quarkus)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Grant execute permission for Gradle
        run: chmod +x ./gradlew

      - name: Build and test backend
        run: ./gradlew build --no-daemon

  frontend:
    name: Frontend (Vue + Vite)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/main/webui

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Build frontend
        run: npm run build
